//
// Datastream.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Datastream: JSONEncodable {

    /** Navigation-Link is the relative URL that retrives content of related entities. */
    public var NavigationLink: String?
    /** Association-Link is the relative URL showing the related entities in other entity types. Only the Self-Links of related entities are returned when resolving Association-Links. */
    public var AssociationLink: String?
    /** This is the description of the datastream entity. The content is open to support other description languages. */
    public var Description: String?
    /** The observations of a datastream observe the same observedProperty. The observations of different datastreams could observe the same observedProperty. */
    public var ObservedProperty: ObservedProperty?
    /** Self-Link is the absolute URL of an entity which is unique among all other entities. */
    public var SelfLink: String?
    /** ID is the system-generated identifier of an entity. ID is unique among the entities of the same entity type. */
    public var ID: String?
    /** A datastream can have zero-to-many observations. One observation must occur in one and only one datastream. */
    public var Observations: [Observation]?
    /** A thing can have zero-to-many datastreams. A datastream entity can only link to a thing as a collection of observations or properties. */
    public var Thing: Thing?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["NavigationLink"] = self.NavigationLink
        nillableDictionary["AssociationLink"] = self.AssociationLink
        nillableDictionary["Description"] = self.Description
        nillableDictionary["ObservedProperty"] = self.ObservedProperty?.encodeToJSON()
        nillableDictionary["SelfLink"] = self.SelfLink
        nillableDictionary["ID"] = self.ID
        nillableDictionary["Observations"] = self.Observations?.encodeToJSON()
        nillableDictionary["Thing"] = self.Thing?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
