//
// Entity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Entity: JSONEncodable {

    /** ID is the system-generated identifier of an entity. ID is unique among the entities of the same entity type. */
    public var ID: String?
    /** Self-Link is the absolute URL of an entity which is unique among all other entities. */
    public var SelfLink: String?
    /** Association-Link is the relative URL showing the related entities in other entity types. Only the Self-Links of related entities are returned when resolving Association-Links. */
    public var AssociationLink: String?
    /** Navigation-Link is the relative URL that retrives content of related entities. */
    public var NavigationLink: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ID"] = self.ID
        nillableDictionary["SelfLink"] = self.SelfLink
        nillableDictionary["AssociationLink"] = self.AssociationLink
        nillableDictionary["NavigationLink"] = self.NavigationLink
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
