//
// ObservedProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ObservedProperty: JSONEncodable {

    /** Navigation-Link is the relative URL that retrives content of related entities. */
    public var Navigation-Link: String?
    /** Association-Link is the relative URL showing the related entities in other entity types. Only the Self-Links of related entities are returned when resolving Association-Links. */
    public var Association-Link: String?
    /** The unit of measurement for the observations measuring this observedProperty. */
    public var UnitOfMeasurement: String?
    public var Datastreams: [Datastream]?
    /** Self-Link is the absolute URL of an entity which is unique among all other entities. */
    public var Self-link: String?
    /** ID is the system-generated identifier of an entity. ID is unique among the entities of the same entity type. */
    public var ID: String?
    /** The URI of the observedProperty/phenomenon. */
    public var URI: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Navigation-Link"] = self.Navigation-Link
        nillableDictionary["Association-Link"] = self.Association-Link
        nillableDictionary["UnitOfMeasurement"] = self.UnitOfMeasurement
        nillableDictionary["Datastreams"] = self.Datastreams?.encodeToJSON()
        nillableDictionary["Self-link"] = self.Self-link
        nillableDictionary["ID"] = self.ID
        nillableDictionary["URI"] = self.URI
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
