//
// Thing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Thing: JSONEncodable {

    /** Navigation-Link is the relative URL that retrives content of related entities. */
    public var Navigation-Link: String?
    /** Association-Link is the relative URL showing the related entities in other entity types. Only the Self-Links of related entities are returned when resolving Association-Links. */
    public var Association-Link: String?
    /** This is the description of the thing entity. The content is open to accommodate changes to SensorML and to support other description languages. */
    public var Description: String?
    /** A thing can have zero-to-many datastreams. A datastream entity can only link to a thing as a collection of observations or properties. */
    public var Datastreams: [Datastream]?
    /** A thing can locate at different geographical positions at different time points (multiple locations). Multiple things can locate at the same location at the same time. A thing may not have a location. */
    public var Locations: [Location]?
    /** Self-Link is the absolute URL of an entity which is unique among all other entities. */
    public var Self-link: String?
    /** ID is the system-generated identifier of an entity. ID is unique among the entities of the same entity type. */
    public var ID: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Navigation-Link"] = self.Navigation-Link
        nillableDictionary["Association-Link"] = self.Association-Link
        nillableDictionary["Description"] = self.Description
        nillableDictionary["Datastreams"] = self.Datastreams?.encodeToJSON()
        nillableDictionary["Locations"] = self.Locations?.encodeToJSON()
        nillableDictionary["Self-link"] = self.Self-link
        nillableDictionary["ID"] = self.ID
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
